services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: jimce
      POSTGRES_PASSWORD: jimce
      POSTGRES_DB: jimce
    volumes:
      - jimce_prod_db_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jimce -d jimce"]
      interval: 1s
      timeout: 1s
      retries: 50
      start_period: 0s

  server:
    image: ghcr.io/jimce-music/jimce-dev:1.0.0-dev-f854713
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://0.0.0.0:8080/api/ping >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - ./config.yml:/app/config.yml # config.yml
      - ./meta.yml:/app/meta.yml # meta.yml
      - ./.env:/app/.env # .env
      - ./logs:/app/logs # Logs

volumes:
  jimce_prod_db_data:
